---
new_page_extension: html
auto_deploy: false
admin_path: "/pub/_cfg"
webhook_url: 
sections:
- type: directory
  path: pub/_pages
  label: pages
  create: all
  match: "*"
  new_doc_ext: md
upload_dir: pub/_assets
public_path: https://raw.githubusercontent.com/aplhatester/newzsite/main/pub/_assets
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: "/_pages"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
